---
dist: xenial
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - "# Update system gems if requested. This is useful to temporarily workaround troubles in the test runner"
  - "# See https://github.com/puppetlabs/pdk-templates/commit/705154d5c437796b821691b707156e1b056d244f for an example of how this was used"
  - '[ -z "$RUBYGEMS_VERSION" ] || gem update --system $RUBYGEMS_VERSION'
  - gem --version
  - bundle -v
script:
  - 'SIMPLECOV=yes bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.3
stages:
  - static
  - spec
  - acceptance
matrix:
  fast_finish: true
  include:
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.5
      stage: spec
    -
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.3
      stage: spec
    -
      before_script: ["bundle exec rake 'litmus:provision_list[travis_deb]'", "bundle exec rake 'litmus:install_agent[puppet5]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      dist: trusty
      env: PLATFORMS=deb_puppet5
      rvm: 2.5.3
      script: ["bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
    -
      before_script: ["bundle exec rake 'litmus:provision_list[travis_deb]'", "bundle exec rake 'litmus:install_agent[puppet6]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      dist: trusty
      env: PLATFORM=deb_puppet6
      rvm: 2.5.3
      script: ["bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
    -
      before_script: ["bundle exec rake 'litmus:provision_list[travis_ub]'", "bundle exec rake 'litmus:install_agent[puppet5]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      dist: trusty
      env: PLATFORMS=ub_puppet5
      rvm: 2.5.3
      script: ["bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
    -
      before_script: ["bundle exec rake 'litmus:provision_list[travis_ub]'", "bundle exec rake 'litmus:install_agent[puppet6]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      dist: trusty
      env: PLATFORM=ub_puppet6
      rvm: 2.5.3
      script: ["bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
    -
      before_script: ["bundle exec rake 'litmus:provision_list[travis_el6]'", "bundle exec rake 'litmus:install_agent[puppet5]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      dist: trusty
      env: PLATFORMS=el6_puppet5
      rvm: 2.5.3
      script: ["bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
    -
      before_script: ["bundle exec rake 'litmus:provision_list[travis_el6]'", "bundle exec rake 'litmus:install_agent[puppet6]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      dist: trusty
      env: PLATFORM=el6_puppet6
      rvm: 2.5.3
      script: ["bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
    -
      before_script: ["bundle exec rake 'litmus:provision_list[travis_el7]'", "bundle exec rake 'litmus:install_agent[puppet5]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      dist: trusty
      env: PLATFORMS=el7_puppet5
      rvm: 2.5.3
      script: ["bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
    -
      before_script: ["bundle exec rake 'litmus:provision_list[travis_el7]'", "bundle exec rake 'litmus:install_agent[puppet6]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      dist: trusty
      env: PLATFORM=el7_puppet6
      rvm: 2.5.3
      script: ["bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
branches:
  only:
    - master
    - /^v\d/
    - release
notifications:
  email: false
  slack:
    secure: XpBD602OXRZHSTDylzzx/OqpfThEJPbx0PLhXctWuES4GpW1EHWnyPgrliNOaJOh0Zb7qMrdaKWLOltfqPT5IanPd0XF7GbT8RrNeLTmLXqvHmC6dDqWxnvFvdSrGwqpj7s7Dbwl79nmszONRj1OlolPmJgY/2kGw88c71biaas=
