---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.0
env:
  global:
    - BEAKER_PUPPET_COLLECTION=puppet6 PUPPET_GEM_VERSION="~> 6.0"
matrix:
  fast_finish: true
  include:
    -
      bundler_args: 
      dist: trusty
      env: PLATFORM=ubuntu:14_16_18
      rvm: 2.5.0
      script:
      - bundle exec rake 'waffle:provision[docker, ubuntu:14.04]'
      - bundle exec rake 'waffle:provision[docker, ubuntu:16.04]'
      - bundle exec rake 'waffle:provision[docker, ubuntu:18.04]' 
      - bundle exec rake waffle:install_agent
      - bundle exec rake waffle:install_module
      - bundle exec rake acceptance:all -j10 -m
      services: docker
      sudo: required
    -
      bundler_args: 
      dist: trusty
      env: PLATFORM=centos:6_7
      rvm: 2.5.0
      script:
      - bundle exec rake 'waffle:provision[docker, centos:6]'
      - bundle exec rake 'waffle:provision[docker, centos:7]'
      - bundle exec rake waffle:install_agent
      - bundle exec rake waffle:install_module
      - bundle exec rake acceptance:all -j10 -m
      services: docker
      sudo: required
    -
      bundler_args:
      dist: trusty
      env: PLATFORM=debian:8_9
      rvm: 2.5.0
      script:
      - bundle exec rake 'waffle:provision[docker, debian:8]'
      - bundle exec rake 'waffle:provision[docker, debian:9]'
      - bundle exec bolt command run 'apt-get install wget -y' --inventoryfile inventory.yaml --nodes='localhost*'
      - bundle exec rake waffle:install_agent
      - bundle exec rake waffle:install_module
      - bundle exec rake acceptance:all -j10 -m
      services: docker
      sudo: required
    -
      env: CHECK="syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
    -
      env: CHECK=parallel_spec
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.4
branches:
  only:
    - master
    - /^v\d/
    - release
notifications:
  email: false
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: ""
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
